version: "3.4"

volumes:
  mariadb_data:

networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mailhog-redmine.rule=Host(`mailhog-redmine.traefik.me`)"
        - "traefik.http.routers.mailhog-redmine-tls.tls.domains[0].main=mailhog-redmine.traefik.me"
        - "traefik.http.routers.mailhog-redmine-tls.tls.domains[0].sans=mailhog-redmine-*.traefik.me"
        - "traefik.http.services.mailhog-redmine.loadbalancer.server.port=8025"
  mariadb:
    image: mariadb:10.6.1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: core
      MYSQL_USER: siteinternet
      MYSQL_PASSWORD: password
      TZ: Europe/Paris
    volumes:
      - mariadb_data:/var/lib/mysql
      - ${PWD}/dump:/dump
    networks:
      - net
    deploy:
      labels:
        - "traefik.enable=false"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - mariadb
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin-redmine.rule=Host(`phpmyadmin-redmine.traefik.me`)"
        - "traefik.http.routers.phpmyadmin-redmine-tls.tls.domains[0].main=phpmyadmin-redmine.traefik.me"
        - "traefik.http.routers.phpmyadmin-redmine-tls.tls.domains[0].sans=phpmyadmin-redmine-*.traefik.me"
        - "traefik.http.services.phpmyadmin-redmine.loadbalancer.server.port=80"
  wwww:
    image: redmine:4.2.1
    networks:
      - net
      - proxynetwork
    depends_on:
      - mariadb
      - mailhog
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.redmine.rule=Host(`redmine.traefik.me`)"
        - "traefik.http.routers.redmine-tls.tls.domains[0].main=redmine.traefik.me"
        - "traefik.http.routers.redmine-tls.tls.domains[0].sans=redmine-*.traefik.me"
        - "traefik.http.services.redmine.loadbalancer.server.port=3000"
